dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
wallets:
  from_key: ${SAMPLE_PRIVATE_KEY}
